openapi: 3.0.2
info:
  title: Arcane Scripts API
  description: API for requesting and retrieving rendered scripts
  version: 'v0.0.2'
servers:
  - description: API Gateway (alpha)
    url: https://tgmospc50f.execute-api.eu-west-2.amazonaws.com/alpha
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/chizovation/ArcaneScripts/v0.0.2

components:
  schemas:
    # types
    RequestId:
      type: string
      nullable: false
      example: 057a3874-625a-41f0-a89a-50799e535f44

    Status:
      type: string
      nullable: false
      enum: [received, processing, complete, failed]
      example: processing

    DownloadURL:
      type: string
      nullable: true
      example: https://somewhere.in.aws/b4f7-4d4acce98986.pdf

    # responses

    ScriptResponse:
      type: object
      properties:
        request_id:
          $ref: '#/components/schemas/RequestId'
        status:
          $ref: '#/components/schemas/Status'
        download_url:
          $ref: '#/components/schemas/DownloadURL'

    ScriptTopLevelResponse:
      type: object
      properties:
        message:
          type: string
          nullable: false
          example: we didn't write this yet
        request_id:
          $ref: '#/components/schemas/RequestId'
        status:
          $ref: '#/components/schemas/Status'

paths:
  /scripts:
    post:
      description: Post a request for a new script to be rendered
      parameters: []
      responses:
        '501':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScriptTopLevelResponse'

  /scripts/{request_id}:
    get:
      description: Retrieve the status of a script request
      parameters:
        - name: request_id
          in: path
          description: The id of the script request
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScriptResponse'
