---
name: Terraform Matrix

# https://github.com/hashicorp/setup-terraform#setup-terraform

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [main]
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  terraform-matrix:
    name: Terraform
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        aws-account-id:
          - 436158765452
        include:
          - account-name-prefix: chizography
            session-tag: infra-arcane-net
            aws-deployment-role: botc/deploy_json2pdf
            terraform-dir: terraform

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run terraform actions
        id: run-terraform-actions
        # yamllint disable-line rule:line-length
        uses: chizmw/terraform-workflow-action@v1
        with:
          # yamllint disable rule:line-length
          use-workspaces: false
          terraform-dir: ${{ matrix.terraform-dir }}
          state-key: ${{ github.repository }}-${{ matrix.aws-account-id }}-${{ matrix.session-tag }}.tfstate
          aws-account-id: ${{ matrix.aws-account-id }}
          aws-account-name-prefix: ${{ matrix.account-name-prefix }}
          aws-session-tag: ${{ matrix.session-tag }}
          aws-access-key-id: ${{ secrets.CHIZOGRAPHY_GITHUB_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CHIZOGRAPHY_GITHUB_AWS_SECRET_ACCESS_KEY }}
          aws-deployment-role: ${{ matrix.aws-deployment-role }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          aws-region: eu-west-2
          # yamllint enable rule:line-length

          # set auto-apply to true if we are running because of a tag creation
          auto-apply: ${{ startsWith(github.ref, 'refs/tags/') }}
